### ISSUE TITLE
Broken Angular PeerDepencies in 4.2.0

### ISSUE THREAD

**Issue by kalik1** [rodgc/ngx-socket-io#127]
In minor a version update, it changes the angular major version in peer dependencies. 
This change, breaks all the ^12.0.0 applications:

in **4.1.0** `package.json`

```
    "@angular/common": "^12.0.0",
    "@angular/core": "^12.0.0"
```
    
in **4.2.0** `package.json`

```
     "@angular/common": "^13.0.0",
     "@angular/core": "^13.0.0"
```

I think that if this angular version dependency is really needed, it should update also this package's major version, otherwise it should not change the `peerDependencies` section in `package.json`.

**Quick fix:**  Set `"ngx-socket-io": "~4.1.0",` in `package.json`

**Comment by sucotronic** [comment]
I've been looking in other angular libraries and they normally change major version number at the same time that the angular dependency changes, even using the same major number.

**Comment by Helveg** [comment]
Sometimes packages lock step their major version with that of their peer dependency, but we have both `socket.io` and `angular`. I think since socket.io is i) less frequently changing major version ii) a less obvious peer iii) invisibly coupled to the server side as well, a more important target to lock step with than Angular. So ngx-socket-io 4.x matches with socket io 4.x

I'd therefore advise you to specify a stricter version constraint for `ngx-socket-io`, so that only patch version updates are automatically installed. We could update the README version support  table to also list which angular versions are supported.

I'm not familiar with `npm` much, but can't we specify laxer peer dependencies? eg include `@angular/common>12,<14`?

**Comment by kalik1** [comment]
As stated in [SemVer](https://semver.org/)  in rule #7, 

> Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards compatible functionality is introduced to the public API. [....] 

In this case the functionality is not backward compatible, because it breaks the public API (in this case the Angular version)..

**Comment by Helveg** [comment]
@rodgc I now have a bit more experience with maintaining JS packages and I agree with this thread: We should drastically relax our peerdependencies. A good plan of action here is:

* Add tests
* Use tests to confirm that we support a wide range of angular versions, and express this as a range in our `peerDependencies`: `14.x - 18.x`
* Whenever we update this range to include new versions, it is a minor version increase
* Whenever we update this range to drop older versions, it is a major version increase
* Whenever there is a specific version of Angular affected by a bug, we exclude it with a patch version increase, and can reinclude newer versions when it is fixed with another patch version increase.
