### ISSUE TITLE
node_modules/ngx-socket-io/src/socket-io.module.d.ts (8,45): Type 'ModuleWithProviders' is not generic.

### ISSUE THREAD

**Issue by waynelidza** [rodgc/ngx-socket-io#88]
ERROR in Error: Metadata version mismatch for module /Users/leewaynemaponga/Downloads/mapbox-app-master/node_modules/ngx-socket-io/ngx-socket-io.d.ts, found version 4, expected 3, resolving symbol AppModule in /Users/leewaynemaponga/Downloads/mapbox-app-master/src/app/app.module.ts, resolving symbol AppModule in /Users/leewaynemaponga/Downloads/mapbox-app-master/src/app/app.module.ts, resolving symbol AppModule in /Users/leewaynemaponga/Downloads/mapbox-app-master/src/app/app.module.t

Angular CLI: 11.2.5
Node: 14.15.5
OS: darwin x64

Angular: 
... 
Ivy Workspace: 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1102.5 (cli-only)
@angular-devkit/core         11.2.5 (cli-only)
@angular-devkit/schematics   11.2.5 (cli-only)
@schematics/angular          11.2.5 (cli-only)

**Comment by jrmykolyn** [comment]
Hi @waynelidza,

Can you please post the version of `ngx-socket-io` that you're currently using?

It looks like the issue you're describing was fixed by the following pull request: https://github.com/rodgc/ngx-socket-io/pull/50. The code was released as part of version `3.1.0`, so you should be able to solve your problem by using that version (or a more recent one).
